/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'UartPacket' message type. See UartPacket.h for more details.
 */

#include <message.h>
#include "UartPacket.h"

uint32_t UartPacket_time_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 32);
}

void UartPacket_time_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 0, 32, value);
}

uint32_t UartPacket_field1_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 32);
}

void UartPacket_field1_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 32, 32, value);
}

uint32_t UartPacket_field2_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 64, 32);
}

void UartPacket_field2_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 64, 32, value);
}

uint32_t UartPacket_field3_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 96, 32);
}

void UartPacket_field3_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 96, 32, value);
}

uint16_t UartPacket_field4_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 128, 16);
}

void UartPacket_field4_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 128, 16, value);
}

uint16_t UartPacket_field5_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 144, 16);
}

void UartPacket_field5_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 144, 16, value);
}

uint16_t UartPacket_field6_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 160, 16);
}

void UartPacket_field6_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 160, 16, value);
}

uint8_t UartPacket_field7_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 176, 8);
}

void UartPacket_field7_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 176, 8, value);
}

uint8_t UartPacket_field8_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 184, 8);
}

void UartPacket_field8_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 184, 8, value);
}

uint8_t UartPacket_type_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 192, 8);
}

void UartPacket_type_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 192, 8, value);
}

